name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: dotnet build 
    - run: dotnet test
    - name: Builds the typescript code
      run: |
        npm install
        npm run build
      working-directory: ./DotnetTemplate.Web
    - name: Runs the linter on the TypeScript code.
      run : npm run lint
      working-directory: ./DotnetTemplate.Web
    - name: Test TS 
      run: npm t
      working-directory: ./DotnetTemplate.Web
  